### ISSUE TITLE
Training datasets

### ISSUE THREAD

**Issue by UnderTheMangoTree** [mlpc-ucsd/BLIVA#10]
Thanks for your work! How can I get the "blip_laion_cc_sbu_558k.json" and "bliva_llava_150k.json"? 
the original llava_150k.json doesn't fit the dataload module, such as "ann["question"]".

**Comment by gordonhu608** [comment]
Thank you for your interest in our work. We acknowledged LLaVA and used their pre-training dataset here: https://huggingface.co/datasets/liuhaotian/LLaVA-Pretrain/blob/main/blip_laion_cc_sbu_558k.json. As for the lava 150k,  it has multiple nested questions and answers in one data. We simply unnested or flatten the data into one question, answer pair per data point.

**Comment by UnderTheMangoTree** [comment]
okay, thanks for your help!😁
