### ISSUE TITLE
Some question about train dataset？

### ISSUE THREAD

**Issue by shipengai** [mlpc-ucsd/BLIVA#14]
As paper says，“Instead, it leverages a more compact 0.5M pre-training caption data following llava”。
It means that “In the first pretrain stage, the train dataset is only [blip_laion_cc_sbu_558k.json](https://huggingface.co/datasets/liuhaotian/LLaVA-Pretrain/blob/main/blip_laion_cc_sbu_558k.json)?”

**Comment by gordonhu608** [comment]
Yes, this is amount of data used for initial alignment.
