### ISSUE TITLE
could you provide the dataset code for visdial and the test code?

### ISSUE THREAD

**Issue by Thinking-more** [mlpc-ucsd/BLIVA#18]

**Comment by gordonhu608** [comment]
Thank you for your interest in our work. For visdial, we directly downloaded their official dataset and the test code is employed as here:  https://github.com/mlpc-ucsd/BLIVA/blob/b45425a7c87d01ecc075d86c9f2376689a1c80db/bliva/models/bliva_vicuna7b.py#L519-L521

**Comment by gordonhu608** [comment]
Yes. As mentioned in the paper, we followed the same evaluation prompt as InstructBLIP. For VisDial, it's like ''<Image> Dialog history: {}\n Question: {} Short answer: '''. Notice that Visual Dialog evaluation needs heavy GPU memory due to its long context nature. Hope this is helpful.

**Comment by gordonhu608** [comment]
Also, as reported, we used Mean Reciprocal Rank (MRR) as the evaluation metric for VisDial. Hope it's helpful.

**Comment by gordonhu608** [comment]
It's the same as we provided before. For which step are you running into problems exactly?

**Comment by gordonhu608** [comment]
Got it, I suggest to run Visdial in our framework. Can you first check your model checkpoint? Are you able to reproduce results for other datasets?

**Comment by gordonhu608** [comment]
We didn't apply special treatment for VisDial, we kept everything as default. Another detail is that, as mentioned in InstructBLIP's paper (section inference), many datasets including VisDial are evaluated using ranked based approach which is in this file https://github.com/mlpc-ucsd/BLIVA/blob/5c64594d15350cc4472fa5e6c64f98bbe34670b3/evaluate.py#L53-L63
