### ISSUE TITLE
Can't download the model weights

### ISSUE THREAD

**Issue by qwqwq1445** [mlpc-ucsd/BLIVA#19]
I tried to download the model weights of BLIVA from this link(https://huggingface.co/mlpc-lab/BLIVA_Vicuna) and failed every time. Could you release the model weights again? Thank you.

**Comment by gordonhu608** [comment]
To download the Gigabyte weight from huggingface, make sure to first do: `git lfs install` and then you can use `git clone https://huggingface.co/mlpc-lab/BLIVA_Vicuna`

**Comment by qwqwq1445** [comment]
> To download the Gigabyte weight from huggingface, make sure to first do: `git lfs install` and then you can use `git clone https://huggingface.co/mlpc-lab/BLIVA_Vicuna`

I do this as your guide and got a Timed Out error from the huggingface. Will you consider release the model weights on the Google Cloud?

**Comment by qwqwq1445** [comment]
> To download the Gigabyte weight from huggingface, make sure to first do: `git lfs install` and then you can use `git clone https://huggingface.co/mlpc-lab/BLIVA_Vicuna`

already solved by  accessing mirror station
