### ISSUE TITLE
Vram? 

### ISSUE THREAD

**Issue by TingTingin** [mlpc-ucsd/BLIVA#3]
How much vram does it take to run this on both the vicuña and flan versions can it be ran on consumer gpus? Also will the trams formers library be supported in the future?

**Comment by gordonhu608** [comment]
Thanks for your interest in our work. It takes around 20G to run vicuna (7B) version with fp16 and around 28G for flant5xxl (11B) version. So vicuna version can be fitted into a consumer gpu (24G).

**Comment by gordonhu608** [comment]
Another way is try using int8, which can save lots of memory without performance drop.

**Comment by gordonhu608** [comment]
Yes, we will support Huggingface model hub soon.

**Comment by gordonhu608** [comment]
We are still investigating int8 inference. Our initial attempt seems not working well. Try deepspeed with cpu could be a good solution.
